const actionTypes = Object.freeze({
  PAGE_A_REQUEST: 'PAGE_A_REQUEST',
  PAGE_A_SUCCESS: 'PAGE_A_SUCCESS',
  PAGE_A_FAILED: 'PAGE_A_FAILED',
  PAGE_B_REQUEST: 'PAGE_B_REQUEST',
  PAGE_B_SUCCESS: 'PAGE_B_SUCCESS',
  PAGE_B_FAILED: 'PAGE_B_FAILED',
  OPEN_MENU_REQUEST: 'OPEN_MENU_REQUEST',
  CLOSE_MENU_REQUEST: 'CLOSE_MENU_REQUEST'
});
export default actionTypes;
